
name: $(Major).$(Minor).$(rev:r)

variables:
  Major: 1
  Minor: 0
  ProjectName: 'andreujuanc.AndreuJuanC.OpenCqrs.Store.InMemory'
  BuildConfiguration: 'Release'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Dotnet test'
  inputs:
    command: 'test'
    projects: './OpenCqrs.Store.InMemory.Test'
    feedsToUse: 'select'
    versioningScheme: 'off'
    
- task: DotNetCoreCLI@2
  displayName: 'Dotnet pack'
  inputs:
    command: 'pack'
    feedsToUse: 'select'
    packagesToPack: './src/AndreuJuanC.OpenCqrs.Store.InMemory.csproj'
    versioningScheme: 'byBuildNumber'
- task: NuGetCommand@2
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget'
    versioningScheme: 'off'
# - task: DotNetCoreCLI@2
#   displayName: 'Dotnet push'
#   inputs:
#     command: 'push'
#     feedsToUse: 'select'
#     packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
#     nuGetFeedType: 'external'
#     publishFeedCredentials: 'Nuget'
#     versioningScheme: 'off'
